body:
  - type: input
    attributes:
      name: pexels_api_key
      label: "Pexels API Key"
      description: "Enter your Pexels API key and restart the flow launcher"
      defaultValue: ""
