name: Publish Release

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths-ignore: 
      - .github/workflows/*

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      python_ver: 3.11

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.python_ver }}

      - name: Get Version from plugin.json
        id: version
        uses: notiz-dev/github-action-json-property@release
        with: 
          path: 'plugin.json'
          prop_path: 'Version'

      - run: echo ${{steps.version.outputs.prop}}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -t ./lib  # Ensures dependencies are in ./lib

      - name: Package Plugin
        run: zip -r Flow.Launcher.Plugin.WallpaperChanger.zip . -x '*.git*'

      - name: Publish Release
        if: success()
        uses: softprops/action-gh-release@v1
        with:
          files: 'Flow.Launcher.Plugin.WallpaperChanger.zip'
          tag_name: "v${{steps.version.outputs.prop}}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
